SRCDIR= ./com/numlang/

SRC = 	$(SRCDIR)NumLang.java\
	$(SRCDIR)BigRational.java\
	$(SRCDIR)Var.java\
	$(SRCDIR)NumValue.java\
	$(SRCDIR)StringValue.java\
	$(SRCDIR)FuncValue.java\
	$(SRCDIR)ListValue.java\
	$(SRCDIR)MatrixValue.java\
	$(SRCDIR)Subroutine.java

default: $(SRC)
	javac $(SRC) 

